server:
  port: 8002
spring:
  application:
    name: stream-consumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    stream:
      bindings:
        #        必须与message.source中@input注解中的value相同
        #        后期可以自定义消息通道，只要保证这两个相同即可（下面这个和注解中的那个）
        input:
          destination: stream.message.zmz #绑定交换机的名字


eureka:
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://localhost:7001/eureka/,http://localhost:7001/eureka/

